#!/bin/bash
# Auto-generated by scheduled task "scp-035-short-upload" (2026-08-01)
# SCP-035 short: generate + upload (public)
cd "$HOME/Developer/youtube-factory/backend" || exit 1

LOG="$HOME/Developer/youtube-factory/backend/scp035_scheduled_run.log"
DONE="$HOME/Developer/youtube-factory/backend/scp035_scheduled_run.done"
rm -f "$DONE"
exec > "$LOG" 2>&1

echo "=== scp-035 scheduled run started: $(date) ==="

# --- VOICEVOX ---
if ! curl -s -m 2 http://localhost:50021/version > /dev/null; then
  echo "VOICEVOX not running — launching..."
  open -a VOICEVOX
  for i in $(seq 1 30); do
    sleep 2
    if curl -s -m 2 http://localhost:50021/version > /dev/null; then
      echo "VOICEVOX is up (waited $((i*2))s)"
      break
    fi
  done
fi
if curl -s -m 2 http://localhost:50021/version > /dev/null; then
  echo "VOICEVOX: OK ($(curl -s -m 2 http://localhost:50021/version))"
else
  echo "WARNING: VOICEVOX still not reachable after 60s — aborting to avoid silent-audio upload"
  echo "EXIT_CODE=90" > "$DONE"
  exit 90
fi

# --- env ---
export $(grep -v '^#' .env | grep -v '^$' | xargs)

export SHORT_THEME_TITLE="SCP-035に装着された7人の研究員が全員別人格になった——財団が仮面を絶対に破壊しない本当の理由"
export SHORT_THEME_ANGLE="SCP-035（取り憑く仮面）個別オブジェクト解説。装着者の人格を完全に乗っ取る仮面。なぜ財団は破壊せず収容を選ぶのか。数字入り断定調。30秒ショート向け。"
export SHORT_TARGET_SEC=30
export SHORT_PRIVACY=public

python3 run_scp_short_upload.py
RC=$?
echo "EXIT_CODE=$RC" > "$DONE"
echo "=== finished: $(date) rc=$RC ==="
exit $RC
